spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/brain?defaultSchema=brain
    username: brain
    password: brain
    hikari:
      auto-commit: false
      schema: brain

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.temp.use_jdbc_metadata_defaults: false

  liquibase:
    change-log: classpath:db/brain-changelog.xml
    enabled: true
    liquibase-schema: brain
    parameters:
      podcast.grant-reading-to: brain

