version: "3.3"


services:

  database:
    image: library/postgres:12
    container_name: brain-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=brain
    ports:
      - 5432:5432
    volumes:
      - ~/work-store/brain/database:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 6s
      retries: 10

  mongodatabase:
    image: 'mongo'
    container_name: ru.fitnes
    environment:
      - MONGO_INITDB_DATABASE=mongo-db-ru.fitnes
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./docker-entrypoint-initdb.d/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ~/work-store/fitnesMongo:/data/db
    ports:
      - '27017-27019:27017-27019'
